{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/__init__.py\", line 26, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/compat/__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/compat/pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/core/api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery.job.copy_ import CopyJob\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/copy_.py\", line 22, in <module>\n",
      "    from google.cloud.bigquery.table import TableReference\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/table.py\", line 33, in <module>\n",
      "    import pyarrow  # type: ignore\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery.job.copy_ import CopyJob\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/copy_.py\", line 22, in <module>\n",
      "    from google.cloud.bigquery.table import TableReference\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/table.py\", line 38, in <module>\n",
      "    import db_dtypes  # type: ignore\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/db_dtypes/__init__.py\", line 28, in <module>\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery.job.copy_ import CopyJob\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/copy_.py\", line 22, in <module>\n",
      "    from google.cloud.bigquery.table import TableReference\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/table.py\", line 62, in <module>\n",
      "    from google.cloud.bigquery import _pandas_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery import _pyarrow_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_pyarrow_helpers.py\", line 22, in <module>\n",
      "    import pyarrow  # type: ignore\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery.job.copy_ import CopyJob\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/copy_.py\", line 22, in <module>\n",
      "    from google.cloud.bigquery.table import TableReference\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/table.py\", line 62, in <module>\n",
      "    from google.cloud.bigquery import _pandas_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 42, in <module>\n",
      "    import db_dtypes  # type: ignore\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/db_dtypes/__init__.py\", line 28, in <module>\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 27, in <module>\n",
      "    from google.cloud.bigquery.job.copy_ import CopyJob\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/copy_.py\", line 22, in <module>\n",
      "    from google.cloud.bigquery.table import TableReference\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/table.py\", line 62, in <module>\n",
      "    from google.cloud.bigquery import _pandas_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 52, in <module>\n",
      "    pyarrow = _versions_helpers.PYARROW_VERSIONS.try_import()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_versions_helpers.py\", line 75, in try_import\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 69, in <module>\n",
      "    from google.cloud.bigquery import _job_helpers\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 47, in <module>\n",
      "    from google.cloud.bigquery import job\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/__init__.py\", line 34, in <module>\n",
      "    from google.cloud.bigquery.job.query import _contains_order_by\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 63, in <module>\n",
      "    import db_dtypes  # type: ignore\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/db_dtypes/__init__.py\", line 28, in <module>\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 26, in <module>\n",
      "    import pandas_gbq.query\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/query.py\", line 13, in <module>\n",
      "    from google.cloud import bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py\", line 35, in <module>\n",
      "    from google.cloud.bigquery.client import Client\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 118, in <module>\n",
      "    pyarrow = _versions_helpers.PYARROW_VERSIONS.try_import()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/google/cloud/bigquery/_versions_helpers.py\", line 75, in try_import\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/bx/t7hf05x17njdvlq05vc970km0000gn/T/ipykernel_37096/3048713233.py\", line 11, in <module>\n",
      "    import pandas_gbq\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py\", line 10, in <module>\n",
      "    from .gbq import Context, context, read_gbq, to_gbq  # noqa\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py\", line 28, in <module>\n",
      "    import pandas_gbq.schema.pandas_to_bigquery\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/schema/pandas_to_bigquery.py\", line 10, in <module>\n",
      "    import db_dtypes\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/db_dtypes/__init__.py\", line 28, in <module>\n",
      "    import pyarrow\n",
      "  File \"/Users/rafa/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "numpy.core.multiarray failed to import",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 11\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mmatplotlib\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpyplot\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mplt\u001b[39;00m\n\u001b[0;32m---> 11\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mshapely\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mgeometry\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Polygon\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mshapely\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m wkt\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/__init__.py:10\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m version \u001b[38;5;28;01mas\u001b[39;00m pandas_gbq_version\n\u001b[1;32m      9\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m _versions_helpers\n\u001b[0;32m---> 10\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mgbq\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Context, context, read_gbq, to_gbq  \u001b[38;5;66;03m# noqa\u001b[39;00m\n\u001b[1;32m     12\u001b[0m sys_major, sys_minor, sys_micro \u001b[38;5;241m=\u001b[39m _versions_helpers\u001b[38;5;241m.\u001b[39mextract_runtime_version()\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m sys_major \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m3\u001b[39m \u001b[38;5;129;01mand\u001b[39;00m sys_minor \u001b[38;5;129;01min\u001b[39;00m (\u001b[38;5;241m7\u001b[39m, \u001b[38;5;241m8\u001b[39m):\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/gbq.py:28\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mquery\u001b[39;00m\n\u001b[1;32m     27\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mschema\u001b[39;00m\n\u001b[0;32m---> 28\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mschema\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpandas_to_bigquery\u001b[39;00m\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas_gbq\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtimestamp\u001b[39;00m\n\u001b[1;32m     31\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pandas_gbq/schema/pandas_to_bigquery.py:10\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtyping\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Any, Optional, Tuple\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mwarnings\u001b[39;00m\n\u001b[0;32m---> 10\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mdb_dtypes\u001b[39;00m\n\u001b[1;32m     11\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcloud\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbigquery\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m schema\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas\u001b[39;00m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/db_dtypes/__init__.py:28\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapi\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mextensions\u001b[39;00m\n\u001b[1;32m     27\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m OutOfBoundsDatetime\n\u001b[0;32m---> 28\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpyarrow\u001b[39;00m\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpyarrow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcompute\u001b[39;00m\n\u001b[1;32m     31\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mdb_dtypes\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m core\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/__init__.py:65\u001b[0m\n\u001b[1;32m     63\u001b[0m _gc_enabled \u001b[38;5;241m=\u001b[39m _gc\u001b[38;5;241m.\u001b[39misenabled()\n\u001b[1;32m     64\u001b[0m _gc\u001b[38;5;241m.\u001b[39mdisable()\n\u001b[0;32m---> 65\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpyarrow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mlib\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01m_lib\u001b[39;00m\n\u001b[1;32m     66\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m _gc_enabled:\n\u001b[1;32m     67\u001b[0m     _gc\u001b[38;5;241m.\u001b[39menable()\n",
      "File \u001b[0;32m~/.pyenv/versions/3.10.6/envs/seagrass/lib/python3.10/site-packages/pyarrow/lib.pyx:37\u001b[0m, in \u001b[0;36minit pyarrow.lib\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: numpy.core.multiarray failed to import"
     ]
    }
   ],
   "source": [
    "# imports\n",
    "import pandas as pd\n",
    "import os\n",
    "import tqdm.auto as tqdm\n",
    "import folium\n",
    "import geopandas as gpd\n",
    "import shapefile\n",
    "import xarray as xr\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas_gbq\n",
    "from shapely.geometry import Polygon\n",
    "from shapely import wkt\n",
    "from google.cloud import bigquery"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "GCP_PROJECT = \"seagrass-lewagon\"\n",
    "GCP_REGION=\"europe-west1\"\n",
    "BQ_DATASET = \"seagrass\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "query = f\"\"\"\n",
    "    SELECT *\n",
    "    FROM `{GCP_PROJECT}.{BQ_DATASET}.merged_features`\n",
    "    \"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/rafa/code/Rafapizarro/seagrass\n"
     ]
    }
   ],
   "source": [
    "! pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from google.cloud import bigquery\n",
    "\n",
    "client = bigquery.Client(project=GCP_PROJECT)\n",
    "query_job = client.query(query)\n",
    "result = query_job.result()\n",
    "merged_features = result.to_dataframe()\n",
    "merged_features.to_csv(\"data/merged_features.csv\", header=True, index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>lat</th>\n",
       "      <th>lon</th>\n",
       "      <th>po4</th>\n",
       "      <th>no3</th>\n",
       "      <th>si</th>\n",
       "      <th>nh4</th>\n",
       "      <th>bottom_temp</th>\n",
       "      <th>chlorophyll</th>\n",
       "      <th>avg_temp</th>\n",
       "      <th>salinity</th>\n",
       "      <th>depth</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>30.3125</td>\n",
       "      <td>19.2083</td>\n",
       "      <td>0.004740</td>\n",
       "      <td>0.051770</td>\n",
       "      <td>2.718759</td>\n",
       "      <td>0.025912</td>\n",
       "      <td>22.069154</td>\n",
       "      <td>-0.604708</td>\n",
       "      <td>22.136564</td>\n",
       "      <td>38.917587</td>\n",
       "      <td>-0.350525</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>30.3125</td>\n",
       "      <td>19.0000</td>\n",
       "      <td>0.004753</td>\n",
       "      <td>0.050061</td>\n",
       "      <td>2.729147</td>\n",
       "      <td>0.025394</td>\n",
       "      <td>22.162248</td>\n",
       "      <td>-0.722136</td>\n",
       "      <td>22.209953</td>\n",
       "      <td>38.972239</td>\n",
       "      <td>-0.350794</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>30.3542</td>\n",
       "      <td>19.2500</td>\n",
       "      <td>0.004700</td>\n",
       "      <td>0.050400</td>\n",
       "      <td>2.751623</td>\n",
       "      <td>0.027028</td>\n",
       "      <td>21.827729</td>\n",
       "      <td>-0.297430</td>\n",
       "      <td>22.157374</td>\n",
       "      <td>38.814760</td>\n",
       "      <td>-0.351566</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>30.3542</td>\n",
       "      <td>19.4167</td>\n",
       "      <td>0.004698</td>\n",
       "      <td>0.053587</td>\n",
       "      <td>2.712808</td>\n",
       "      <td>0.027708</td>\n",
       "      <td>21.997698</td>\n",
       "      <td>-1.146987</td>\n",
       "      <td>22.087574</td>\n",
       "      <td>38.823783</td>\n",
       "      <td>-0.351150</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>30.3542</td>\n",
       "      <td>18.9583</td>\n",
       "      <td>0.004712</td>\n",
       "      <td>0.047527</td>\n",
       "      <td>2.762069</td>\n",
       "      <td>0.025768</td>\n",
       "      <td>22.072648</td>\n",
       "      <td>-0.344697</td>\n",
       "      <td>22.249211</td>\n",
       "      <td>38.893303</td>\n",
       "      <td>-0.351799</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96512</th>\n",
       "      <td>45.6458</td>\n",
       "      <td>13.4167</td>\n",
       "      <td>0.017160</td>\n",
       "      <td>4.179916</td>\n",
       "      <td>5.616475</td>\n",
       "      <td>0.470007</td>\n",
       "      <td>17.324449</td>\n",
       "      <td>-0.495972</td>\n",
       "      <td>16.857247</td>\n",
       "      <td>36.523517</td>\n",
       "      <td>-0.460568</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96513</th>\n",
       "      <td>45.6458</td>\n",
       "      <td>13.4583</td>\n",
       "      <td>0.018525</td>\n",
       "      <td>5.002612</td>\n",
       "      <td>6.025208</td>\n",
       "      <td>0.506424</td>\n",
       "      <td>17.275804</td>\n",
       "      <td>-0.923330</td>\n",
       "      <td>16.805123</td>\n",
       "      <td>36.621604</td>\n",
       "      <td>-0.461311</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96514</th>\n",
       "      <td>45.6458</td>\n",
       "      <td>13.1667</td>\n",
       "      <td>0.026258</td>\n",
       "      <td>4.307854</td>\n",
       "      <td>5.868522</td>\n",
       "      <td>0.534417</td>\n",
       "      <td>17.319293</td>\n",
       "      <td>-0.552241</td>\n",
       "      <td>16.894640</td>\n",
       "      <td>36.188888</td>\n",
       "      <td>-0.455058</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96515</th>\n",
       "      <td>45.6458</td>\n",
       "      <td>13.7083</td>\n",
       "      <td>0.029593</td>\n",
       "      <td>9.241012</td>\n",
       "      <td>8.483284</td>\n",
       "      <td>0.823492</td>\n",
       "      <td>16.308663</td>\n",
       "      <td>-0.639466</td>\n",
       "      <td>16.808206</td>\n",
       "      <td>37.649041</td>\n",
       "      <td>-0.469226</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96516</th>\n",
       "      <td>45.6458</td>\n",
       "      <td>13.5000</td>\n",
       "      <td>0.021731</td>\n",
       "      <td>5.914501</td>\n",
       "      <td>6.591555</td>\n",
       "      <td>0.572491</td>\n",
       "      <td>17.060652</td>\n",
       "      <td>-0.927391</td>\n",
       "      <td>16.815045</td>\n",
       "      <td>36.880559</td>\n",
       "      <td>-0.462862</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>96517 rows × 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           lat      lon       po4       no3        si       nh4  bottom_temp  \\\n",
       "0      30.3125  19.2083  0.004740  0.051770  2.718759  0.025912    22.069154   \n",
       "1      30.3125  19.0000  0.004753  0.050061  2.729147  0.025394    22.162248   \n",
       "2      30.3542  19.2500  0.004700  0.050400  2.751623  0.027028    21.827729   \n",
       "3      30.3542  19.4167  0.004698  0.053587  2.712808  0.027708    21.997698   \n",
       "4      30.3542  18.9583  0.004712  0.047527  2.762069  0.025768    22.072648   \n",
       "...        ...      ...       ...       ...       ...       ...          ...   \n",
       "96512  45.6458  13.4167  0.017160  4.179916  5.616475  0.470007    17.324449   \n",
       "96513  45.6458  13.4583  0.018525  5.002612  6.025208  0.506424    17.275804   \n",
       "96514  45.6458  13.1667  0.026258  4.307854  5.868522  0.534417    17.319293   \n",
       "96515  45.6458  13.7083  0.029593  9.241012  8.483284  0.823492    16.308663   \n",
       "96516  45.6458  13.5000  0.021731  5.914501  6.591555  0.572491    17.060652   \n",
       "\n",
       "       chlorophyll   avg_temp   salinity     depth  \n",
       "0        -0.604708  22.136564  38.917587 -0.350525  \n",
       "1        -0.722136  22.209953  38.972239 -0.350794  \n",
       "2        -0.297430  22.157374  38.814760 -0.351566  \n",
       "3        -1.146987  22.087574  38.823783 -0.351150  \n",
       "4        -0.344697  22.249211  38.893303 -0.351799  \n",
       "...            ...        ...        ...       ...  \n",
       "96512    -0.495972  16.857247  36.523517 -0.460568  \n",
       "96513    -0.923330  16.805123  36.621604 -0.461311  \n",
       "96514    -0.552241  16.894640  36.188888 -0.455058  \n",
       "96515    -0.639466  16.808206  37.649041 -0.469226  \n",
       "96516    -0.927391  16.815045  36.880559 -0.462862  \n",
       "\n",
       "[96517 rows x 11 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged_features = pd.read_csv(\"data/merged_features.csv\")\n",
    "merged_features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "import folium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Map saved as 'mediterranean_map.html'. Open it in a browser to view.\n"
     ]
    }
   ],
   "source": [
    "# Define the center of the Mediterranean for the map\n",
    "mediterranean_center = [34.5, 18.0]  # Approximate central coordinates\n",
    "\n",
    "# Create a Folium map\n",
    "m = folium.Map(location=mediterranean_center, zoom_start=5)\n",
    "\n",
    "# Add points to the map\n",
    "for _, row in merged_features.iterrows():\n",
    "    folium.CircleMarker(\n",
    "        location=[row[\"lat\"], row[\"lon\"]],\n",
    "        radius=2,  # Small dot for each point\n",
    "        color=\"blue\",\n",
    "        fill=True,\n",
    "        fill_color=\"blue\",\n",
    "        fill_opacity=0.6\n",
    "    ).add_to(m)\n",
    "\n",
    "# Save and display the map\n",
    "m.save(\"mediterranean_map.html\")\n",
    "print(\"✅ Map saved as 'mediterranean_map.html'. Open it in a browser to view.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "seagrass",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
